### ISSUE TITLE
TypeError: prettierMarkdown.parsers.markdown.preprocess is not a function

### ISSUE THREAD

**Issue by hinricht** [rstacruz/prettier-plugin-markdown-code-fences#1]
Seems like the plugin doesn't work anymore with current prettier (v 3.3.3): 

```sh
$ cat test.md 
# This is a Markdown file

Here are some terminal commands.

    cd /
    find . -name systemd
    uname -a

$ prettier test.md --plugin=@rstacruz/prettier-plugin-markdown-code-fences 
test.md
[error] test.md: TypeError: prettierMarkdown.parsers.markdown.preprocess is not a function
[error]     at Object.preprocess (/home/varac/projects/presentations/varac-slides-internal/slidev/mise/node_modules/@rstacruz/prettier-plugin-markdown-code-fences/index.js:8:56)
[error]     at parse4 (file:///home/varac/.local/share/nvim/mason/packages/prettier/node_modules/prettier/index.mjs:20681:43)
[error]     at async coreFormat (file:///home/varac/.local/share/nvim/mason/packages/prettier/node_modules/prettier/index.mjs:21146:7)
[error]     at async formatWithCursor (file:///home/varac/.local/share/nvim/mason/packages/prettier/node_modules/prettier/index.mjs:21348:14)
[error]     at async formatFiles (file:///home/varac/.local/share/nvim/mason/packages/prettier/node_modules/prettier/internal/cli.mjs:3468:18)
[error]     at async main (file:///home/varac/.local/share/nvim/mason/packages/prettier/node_modules/prettier/internal/cli.mjs:3876:5)
[error]     at async Module.run (file:///home/varac/.local/share/nvim/mason/packages/prettier/node_modules/prettier/internal/cli.mjs:3822:5)
```

**Comment by jfeldstein-cw** [comment]
You can use https://github.com/rstacruz/prettier-plugin-markdown-code-fences/pull/2 now
